#!/usr/bin/Rscript

install.packages("pak")
pak::pkg_install(c("devtools", "remotes", "tidyverse", "shiny", "r2d3", "shinyjs", "DBI", "RSQLite", "jsonlite"))

# timeR just was removed from CRAN on 2026-03-20
pak::pak("yusuzech/timeR")

pak::pak("abbey-thomas/speechcollectr")
